[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool = "1.0.3"
chrono = "0.4.23"
clap = "2.34.0"
enum-iterator = "1.2.0"
regex = "1.7.0"
